# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Prem Ganeshkumar
tagline:          'personal site'
description:      'The personal site of Prem Ganeshkumar, NLP engineer at <a href="http://agolo.com" target="_blank">Agolo</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'Prem Ganeshkumar'
  url:            https://twitter.com/premgane

paginate:         5
